import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } });
const errs=[];
p.on('pageerror', e => errs.push('PAGEERROR: '+e.message.slice(0,150)));
await p.goto('http://localhost:4199/', { waitUntil:'networkidle' });
await p.waitForTimeout(1200);
const info = await p.evaluate(() => {
  const root=document.getElementById('root');
  const q=s=>document.querySelector(s);
  const cta=[...document.querySelectorAll('a,button')].filter(e=>/전형|자세히|학부|알아|보기|바로/.test(e.textContent||''));
  const out={rootLen:root?root.innerHTML.length:-1, totalEls:document.querySelectorAll('*').length};
  const grab=el=>{const cs=getComputedStyle(el);const r=el.getBoundingClientRect();return {t:(el.textContent||'').trim().slice(0,24),radius:cs.borderRadius,bg:cs.backgroundColor,dur:cs.transitionDuration,prop:cs.transitionProperty,w:Math.round(r.width),h:Math.round(r.height)};};
  out.buttons=[...document.querySelectorAll('a[class*="brand-strong"],a[class*="radius"],span[class*="radius-pill"]')].slice(0,8).map(grab);
  const card=q('.card'); out.card=card?grab(card):null;
  return out;
});
console.log(JSON.stringify(info,null,1));
console.log('ERRS',errs);
await p.screenshot({path:'E:/testFront/_shot_home.png'});
await b.close();
